import { useEffect, useState } from "react";
import {
  ArrowLeft, ArrowUpRight, Award, BrainCircuit, ChevronLeft, Code2, Database, Download,
  ExternalLink, Film, Gamepad2, Globe2, Image as ImageIcon, Layers3, Linkedin, Mail, Menu,
  Network, Play, Sparkles, Terminal, X,
} from "lucide-react";

const DRIVE_FOLDER = "https://drive.google.com/drive/folders/1h1vuEhA6J2MeSeuAPda1Pw8k9eg_CETp?usp=sharing";
const LINKEDIN = "https://www.linkedin.com/in/besan-alamri-816722250?utm_source=share_via&utm_content=profile&utm_medium=member_ios";
const EMAIL = "almrybysan18@gmail.com";

const projects = [
  { number: "01", title: "مختبر الزراعة الرقمية الذكية", titleEn: "Smart Digital Agriculture Lab", english: "Smart Digital Agriculture Lab", category: "Web experience", categoryAr: "تجربة ويب", description: "تجربة ويب تفاعلية تستكشف كيف يمكن للبيانات والذكاء الاصطناعي أن يقدما حلولًا أذكى للزراعة الحديثة.", descriptionEn: "An interactive web experience exploring how data and AI can shape smarter solutions for modern agriculture.", tags: ["HTML", "AI concept", "Interactive"], accent: "violet", icon: Globe2, image: "https://lh3.googleusercontent.com/drive-storage/AJQWtBMw8ISsNXCJjT057m4ee9Hwrn8D25mTqODMWYbR93Q70pHCvkIC-KT8jLwEr3oweerQWNKJn0Ia5fd2DvXPc5ZDpu_xu_1ThdDwQSR1GeN_rTihpQ=s600", href: "https://drive.google.com/file/d/1w2UdQq3W6g-N_8ETeno9pnmlrKm_e7zD/view?usp=drivesdk" },
  { number: "02", title: "Smart Delivery Box", titleEn: "Smart Delivery Box", english: "Smart Delivery Box", category: "Product concept", categoryAr: "تصوّر منتج", description: "هوية بصرية وتصوّر لمنتج توصيل ذكي يربط بين التقنية، الأمان، وتجربة المستخدم في مشهد واحد.", descriptionEn: "A visual identity and product concept connecting technology, safety, and user experience in one clear system.", tags: ["Visual design", "Concept", "Product"], accent: "cyan", icon: Layers3, image: "https://lh3.googleusercontent.com/drive-storage/AJQWtBMr2wgkFyyU2l3NWOV5r0UpG1iSzyXwZglTqhJ5vdW9D9sbeOzxQ8MknNMoB8bfqVpUwtFCTWr_dKLB4kDx4-Qh-vahus9j1lXICETjsXWJL0pxYQ=s600", href: "https://drive.google.com/file/d/13JPY5Oxb_O2__37BCIi-3WJUUF1TzkkC/view?usp=drivesdk" },
  { number: "03", title: "تجارب تفاعلية للتعلّم", titleEn: "Interactive learning experiments", english: "Interactive learning experiments", category: "Creative coding", categoryAr: "برمجة إبداعية", description: "ألعاب وتجارب تعليمية تحوّل المفاهيم العلمية إلى لحظات تفاعلية سهلة الفهم وممتعة الاستكشاف.", descriptionEn: "Educational games and experiments that turn scientific ideas into approachable, playful interactions.", tags: ["JavaScript", "Learning", "Game"], accent: "pink", icon: Gamepad2, image: "https://lh3.googleusercontent.com/drive-storage/AJQWtBP8O1Hgn-qE2dI4ge-oHIkVyl6r42fQwqe8HOoDzqA9xfKxxmV9sTuXXJTROpEJjznCntqwU1FvBoOdMxpmPCqyK1fqZvvQKL3L9iPRb-jWZT6Knw=s600", href: "https://drive.google.com/file/d/1gFVyfRXxLHG27R7bgdOzKGLdovkDL05y/view?usp=drivesdk" },
];

const services = [
  { icon: Code2, title: "Full Stack Development", titleAr: "تطوير Full Stack", text: "واجهات عملية، منطق واضح، وتجارب رقمية مصممة حول المستخدم.", textEn: "Practical interfaces, clear logic, and digital experiences designed around people." },
  { icon: BrainCircuit, title: "AI & Creative Tech", titleAr: "الذكاء الاصطناعي والتقنية الإبداعية", text: "أفكار تجمع الذكاء الاصطناعي بالتصميم لتصنع حلولًا أقرب للإنسان.", textEn: "Ideas that bring AI and design together to create more human solutions." },
  { icon: Network, title: "Networking Foundations", titleAr: "أساسيات الشبكات", text: "فهم أساسيات الشبكات والبنية التي تجعل المنتجات الرقمية أكثر موثوقية.", textEn: "A foundation in networks and infrastructure for more reliable digital products." },
];

const certificates = [
  { icon: BrainCircuit, title: "أساسيات الذكاء الاصطناعي", titleEn: "AI Fundamentals", meta: "Artificial Intelligence Fundamentals", color: "violet" },
  { icon: Network, title: "أساسيات الشبكات", titleEn: "Networking Fundamentals", meta: "Networking Fundamentals", color: "cyan" },
  { icon: Award, title: "TOT", titleEn: "Training of Trainers", meta: "Training of Trainers", color: "pink" },
];

function SectionHeading({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) {
  return <div className="section-heading"><p className="eyebrow"><span /> {eyebrow}</p><h2>{title}</h2><p className="section-copy">{copy}</p></div>;
}

function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [language, setLanguage] = useState<"ar" | "en">("ar");
  const [scrollProgress, setScrollProgress] = useState(0);
  const isEn = language === "en";

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = isEn ? "ltr" : "rtl";
    const items = document.querySelectorAll<HTMLElement>(".scroll-reveal");
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add("is-visible"); observer.unobserve(entry.target); } }), { threshold: 0.12 });
    items.forEach((item) => observer.observe(item));
    const updateProgress = () => {
      const scrollable = document.documentElement.scrollHeight - window.innerHeight;
      setScrollProgress(scrollable > 0 ? (window.scrollY / scrollable) * 100 : 0);
    };
    updateProgress();
    window.addEventListener("scroll", updateProgress, { passive: true });
    return () => { observer.disconnect(); window.removeEventListener("scroll", updateProgress); };
  }, [language, isEn]);

  const closeMenu = () => setMenuOpen(false);
  const nav = isEn ? { about: "About", services: "Services", work: "Work", credentials: "Credentials", contact: "Contact" } : { about: "عني", services: "ما أقدمه", work: "أعمالي", credentials: "الشهادات", contact: "تواصل" };

  return (
    <main dir={isEn ? "ltr" : "rtl"} className={`site-shell ${isEn ? "lang-en" : ""}`}>
      <div className="ambient ambient-one" /><div className="ambient ambient-two" />
      <div className="scroll-progress" style={{ "--progress": `${scrollProgress}%` } as React.CSSProperties} aria-hidden="true"><span /></div>
      <header className="site-header"><div className="container header-inner">
        <a href="#top" className="brand" onClick={closeMenu} aria-label="Home"><span className="brand-mark">BA<span>.</span></span><span className="brand-copy"><strong>{isEn ? "Besan Alomari" : "بيسان العمري"}</strong><small>AI · Full Stack</small></span></a>
        <nav className={`main-nav ${menuOpen ? "is-open" : ""}`}><a href="#about" onClick={closeMenu}>{nav.about}</a><a href="#services" onClick={closeMenu}>{nav.services}</a><a href="#work" onClick={closeMenu}>{nav.work}</a><a href="#credentials" onClick={closeMenu}>{nav.credentials}</a><a href="#contact" onClick={closeMenu}>{nav.contact}</a></nav>
        <div className="header-actions"><button className="language-toggle" onClick={() => setLanguage(isEn ? "ar" : "en")} aria-label="Switch language"><span className={!isEn ? "active" : ""}>ع</span><i>/</i><span className={isEn ? "active" : ""}>EN</span></button><a href={`mailto:${EMAIL}`} className="header-cta">{isEn ? "Let's talk" : "لنتحدث"} <ArrowUpRight size={15} /></a><button className="menu-toggle" aria-label={menuOpen ? "Close menu" : "Open menu"} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={22} /> : <Menu size={22} />}</button></div>
      </div></header>

      <section id="top" className="hero-section section-pad"><div className="container hero-grid">
        <div className="hero-content reveal-up"><div className="hero-system-line"><span>{isEn ? "BA / 01" : "بيسان / 01"}</span><span>BUILD 2026.09</span><span>{isEn ? "HUMAN SIGNAL ACTIVE" : "الإشارة البشرية نشطة"}</span></div><div className="status-pill"><span className="pulse-dot" /> {isEn ? "Available for new opportunities" : "متاحة لفرص وتعاونات جديدة"}</div><p className="hero-kicker">Computer Engineer <span>+</span> Creative Technologist</p><h1>{isEn ? <>I build digital<br /><em>experiences that think.</em></> : <>أبني تجارب<br />رقمية <em>تفكّر بذكاء.</em></>}</h1><p className="hero-lead">{isEn ? "I’m Besan Alomari, a computer engineer and full-stack developer. I turn ideas into products that connect code, AI, and thoughtful design." : "أنا بيسان العمري، مهندسة حاسوب ومطوّرة Full Stack. أترجم الأفكار إلى منتجات وتجارب تجمع بين الكود، الذكاء الاصطناعي، والتصميم الواضح."}</p><div className="hero-actions"><a href="#work" className="button button-primary">{isEn ? "Explore my work" : "استكشف الأعمال"} <ArrowLeft size={18} /></a><a href={LINKEDIN} target="_blank" rel="noreferrer" className="button button-ghost">LinkedIn <ExternalLink size={16} /></a></div><div className="hero-metrics"><div><strong>03<span>+</span></strong><small>{isEn ? "areas I work in" : "مجالات أقدّم فيها"}</small></div><div><strong>∞</strong><small>{isEn ? "curiosity to learn" : "فضول للتعلّم"}</small></div><div><strong>01</strong><small>{isEn ? "clear builder mindset" : "عقلية تبني بوضوح"}</small></div></div></div>
        <div className="hero-visual reveal-scale" aria-label={isEn ? "Portrait of Besan Alomari" : "الصورة الشخصية لبيسان العمري"}><div className="code-orbit orbit-back"><span>&lt;/&gt;</span><span>01</span><span>{"{}"}</span><span>AI</span><span>0110</span></div><div className="code-orbit orbit-front"><span>const</span><span>build()</span><span>return</span><span>;</span></div><div className="portrait-halo"><div className="halo-line" /><div className="portrait-frame"><img src="/manus-storage/profile_face_shoulders_44dbb97a.jpeg" alt="Besan Alomari" /></div></div><div className="visual-caption caption-top"><span>01</span><small>curious mind</small></div><div className="visual-caption caption-bottom"><span>02</span><small>build with purpose</small></div><div className="floating-chip chip-ai"><Sparkles size={14} /> AI / HUMAN</div><div className="floating-chip chip-code"><Terminal size={14} /> &lt;code /&gt;</div></div>
      </div><div className="scroll-note"><span>{isEn ? "Scroll to explore" : "مرّري للاستكشاف"}</span><div className="scroll-line" /></div></section>

      <section id="about" className="about-section section-pad section-dark"><div className="container about-grid"><div className="about-aside"><span className="vertical-label">PROFILE / 01</span><div className="aside-line" /></div><div className="about-copy"><SectionHeading eyebrow={isEn ? "A little about me" : "نبذة قصيرة"} title={isEn ? "Technology is not the goal. It is my language for creating impact." : "التقنية عندي ليست غاية، بل لغة لصناعة أثر."} copy={isEn ? "The best products feel simple to people because they are built with intention behind the scenes." : "أؤمن أن أفضل المنتجات هي التي تبدو بسيطة للمستخدم، لأنها مبنية بعناية خلف الكواليس."} /><div className="about-text-grid"><p>{isEn ? <>I love working where <strong>logic meets creativity</strong> — from building interfaces to shaping interactive ideas. I learn constantly, experiment quickly, and treat every project as a chance to understand something new.</> : <>من تطوير الواجهات إلى بناء الأفكار التفاعلية، أحب أن أعمل في المساحة التي يلتقي فيها <strong>المنطق بالإبداع</strong>. أتعلم باستمرار، أجرّب بسرعة، وأحوّل كل مشروع إلى فرصة لفهم شيء جديد.</>}</p><p>{isEn ? "My background in computer engineering, networking, and AI gives me a complete perspective for building digital experiences that are resilient, beautiful, and ready to grow." : "خلفيتي في هندسة الحاسوب، الشبكات، والذكاء الاصطناعي تمنحني منظورًا متكاملًا لبناء تجارب رقمية متينة، جميلة، وقابلة للتطور."}</p></div><div className="signature-row"><span className="signature">Besan<span>.</span></span><span className="signature-note">computer engineer / creative builder</span></div></div></div></section>

      <section id="services" className="services-section section-pad"><div className="container"><SectionHeading eyebrow={isEn ? "What I do" : "ماذا أقدّم"} title={isEn ? "From the first idea to the final experience." : "من الفكرة الأولى إلى التجربة الأخيرة."} copy={isEn ? "I combine engineering thinking and visual sensitivity to build work with a clear purpose and a distinct personality." : "أجمع بين التفكير الهندسي والحسّ البصري لأبني أعمالًا لها وظيفة واضحة وشخصية مميزة."} /><div className="services-grid">{services.map(({ icon: Icon, title, titleAr, text, textEn }, index) => <article className="service-card scroll-reveal" style={{ "--delay": `${index * 90}ms` } as React.CSSProperties} key={title}><div className="card-icon"><Icon size={23} /></div><span className="card-index">0{index + 1}</span><h3>{isEn ? title : titleAr}</h3><p>{isEn ? textEn : text}</p><a href="#work">{isEn ? "Explore this path" : "اكتشف المسار"} <ArrowLeft size={16} /></a></article>)}</div></div></section>

      <section className="principles-section section-pad section-dark"><div className="container"><div className="principles-head"><SectionHeading eyebrow={isEn ? "My build philosophy" : "فلسفتي في البناء"} title={isEn ? "Human signal, translated into useful systems." : "إشارة بشرية، أترجمها إلى أنظمة مفيدة."} copy={isEn ? "A simple four-step lens I bring to every interface, experiment, and product idea." : "عدسة من أربع مراحل أستخدمها مع كل واجهة، تجربة، وفكرة منتج."} /><span className="system-status"><i /> {isEn ? "SYSTEM / EVOLVING" : "النظام / يتطور"}</span></div><div className="principles-grid">{(isEn ? [{ key: "01 / NOTICE", title: "Listen first", text: "Understand the person, the context, and the signal behind the request." }, { key: "02 / CONNECT", title: "Map the system", text: "Turn complexity into a clear flow where technology serves the idea." }, { key: "03 / BUILD", title: "Make it tangible", text: "Prototype with energy, test the edges, and let the work speak." }, { key: "04 / EVOLVE", title: "Keep it alive", text: "Leave room for learning, iteration, and a better next version." }] : [{ key: "01 / NOTICE", title: "أصغي أولًا", text: "أفهم الشخص والسياق والإشارة التي تقف خلف الطلب." }, { key: "02 / CONNECT", title: "أرسم النظام", text: "أحوّل التعقيد إلى مسار واضح تخدم فيه التقنية الفكرة." }, { key: "03 / BUILD", title: "أجعلها ملموسة", text: "أصنع نموذجًا سريعًا، أختبر التفاصيل، وأدع العمل يتحدث." }, { key: "04 / EVOLVE", title: "أتركها حيّة", text: "أترك مساحة للتعلم والتكرار والنسخة الأفضل القادمة." }]).map((item, index) => <article className="principle-card scroll-reveal" style={{ "--delay": `${index * 100}ms` } as React.CSSProperties} key={item.key}><span className="principle-key">{item.key}</span><span className="principle-symbol">{["◌", "⌁", "✦", "↗"][index]}</span><h3>{item.title}</h3><p>{item.text}</p><ArrowUpRight className="principle-arrow" size={17} /></article>)}</div></div></section>

      <section id="work" className="work-section section-pad section-dark"><div className="container"><div className="work-head"><SectionHeading eyebrow={isEn ? "Selected work" : "مختارات من الحقيبة"} title={isEn ? "Curiosity, turned into something you can see." : "أعمال تحوّل الفضول إلى شيء يمكن رؤيته."} copy={isEn ? "A selection of projects and experiments from my portfolio. Open any project to view its full file." : "مجموعة مختارة من المشاريع والتجارب الموجودة داخل حقيبة الأعمال. اضغطي على أي مشروع لفتح ملفه الكامل."} /><a className="text-link" href={DRIVE_FOLDER} target="_blank" rel="noreferrer">{isEn ? "Open portfolio folder" : "فتح حقيبة الأعمال"} <ExternalLink size={16} /></a></div><div className="projects-list">{projects.map((project, index) => { const Icon = project.icon; return <article className={`project-row accent-${project.accent} scroll-reveal`} style={{ "--delay": `${index * 130}ms` } as React.CSSProperties} key={project.number}><div className="project-meta"><span className="project-number">{project.number}</span><span className="project-category">{isEn ? project.category : project.categoryAr}</span><Icon size={18} /></div><div className="project-image-wrap"><img src={project.image} alt={isEn ? project.titleEn : project.title} /><div className="image-overlay"><Play size={19} fill="currentColor" /></div></div><div className="project-info"><p className="project-english">{project.english}</p><h3>{isEn ? project.titleEn : project.title}</h3><p>{isEn ? project.descriptionEn : project.description}</p><div className="tag-row">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div></div><a href={project.href} target="_blank" rel="noreferrer" className="project-link" aria-label={`Open ${project.titleEn}`}><ArrowUpRight size={20} /></a></article>; })}</div><div className="archive-banner"><div><ImageIcon size={19} /><span>{isEn ? "More visual experiments, games, and videos live in the full archive." : "المزيد من التجارب البصرية، الألعاب، والفيديوهات داخل الأرشيف الكامل."}</span></div><a href={DRIVE_FOLDER} target="_blank" rel="noreferrer">{isEn ? "View all" : "استعراض الكل"} <ChevronLeft size={17} /></a></div></div></section>

      <section id="credentials" className="credentials-section section-pad"><div className="container credentials-grid"><div><SectionHeading eyebrow={isEn ? "Keep learning" : "التعلّم المستمر"} title={isEn ? "Credentials build the foundation. Curiosity expands the horizon." : "شهادات تبني الأساس، وفضول يوسّع الأفق."} copy={isEn ? "These are not the end of the journey — they are bright markers in an ongoing path of learning and making." : "هذه ليست نهاية الرحلة؛ إنها نقاط مضيئة في مسار مستمر من التعلّم والتجريب."} /><a href={DRIVE_FOLDER} target="_blank" rel="noreferrer" className="button button-outline"><Download size={17} /> {isEn ? "View certificates & files" : "استعراض الملفات والشهادات"}</a></div><div className="certificate-stack">{certificates.map((certificate, index) => { const Icon = certificate.icon; return <div className={`certificate-card cert-${certificate.color} scroll-reveal`} style={{ "--delay": `${index * 110}ms` } as React.CSSProperties} key={certificate.title}><div className="certificate-icon"><Icon size={20} /></div><div><strong>{isEn ? certificate.titleEn : certificate.title}</strong><span>{certificate.meta}</span></div><span className="certificate-no">0{index + 1}</span></div>; })}</div></div></section>

      <section id="contact" className="contact-section section-pad section-dark"><div className="container contact-card"><div className="contact-orb orb-left" /><div className="contact-orb orb-right" /><div className="contact-inner"><p className="eyebrow"><span /> {isEn ? "Let's make something good" : "لنصنع شيئًا جيدًا"}</p><h2>{isEn ? <>Have an idea?<br /><em>Let’s talk about it.</em></> : <>لديك فكرة؟<br /><em>لنتحدث عنها.</em></>}</h2><p>{isEn ? "A project, an opportunity, or a curious question — I’d love to hear from you." : "إذا كان لديك مشروع، فرصة، أو حتى سؤال فضولي — يسعدني أن أسمع منك."}</p><a href={`mailto:${EMAIL}`} className="email-link">{EMAIL} <ArrowUpRight size={19} /></a><div className="contact-links"><a href={LINKEDIN} target="_blank" rel="noreferrer"><Linkedin size={17} /> LinkedIn</a><a href={DRIVE_FOLDER} target="_blank" rel="noreferrer"><Database size={17} /> {isEn ? "Portfolio folder" : "حقيبة الأعمال"}</a></div></div></div></section>
      <footer className="site-footer"><div className="container footer-inner"><span>© 2026 Besan Alomari</span><span>{isEn ? "Built with code & curiosity" : "مصمّمة بالكود والفضول"} <Sparkles size={14} /></span><a href="#top">{isEn ? "Back to top" : "العودة للأعلى"} <ArrowLeft size={15} /></a></div></footer>
    </main>
  );
}

export default Home;
